# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Standard', models.CharField(max_length=200)),
                ('My_goal_for_this_week', models.CharField(max_length=200)),
                ('What_I_did_today_towards_my_goals', models.TextField()),
                ('How_did_I_feel_after_my_assessment', models.TextField()),
                ('Work_I_did_at_home', models.TextField()),
                ('What_can_I_do_now_that_I_could_not_do_last_week', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
