# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170513_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='My_goal_for_this_week',
            field=models.CharField(choices=[('TRU', 'trucks'), ('WRI', 'writing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Name',
            field=models.CharField(choices=[('LAB', 'labor'), ('CAR', 'cars'), ('TRU', 'trucks'), ('WRI', 'writing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Standard',
            field=models.CharField(choices=[('7th STD', '7th STD'), ('8th STD', '8th STD'), ('9th STD', '9th STD')], max_length=200),
        ),
    ]
