# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170613_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='Name',
            field=models.TextField(default='Sanjeev'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Chapter',
            field=models.TextField(default='Some 7th chapter'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal',
            field=models.TextField(default='Some goal'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Standard',
            field=models.TextField(default='Grade 7th'),
        ),
    ]
