# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170613_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='Goal',
            new_name='Goal_old1',
        ),
        migrations.AddField(
            model_name='post1',
            name='Goal_old2',
            field=models.TextField(default='Some goal'),
        ),
    ]
