# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170613_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What_did_I_do_at_home', models.TextField()),
                ('What_I_did_towards_my_goals', models.TextField()),
            ],
        ),
    ]
