# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 17, 2, 55, 46, 686037)),
        ),
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 17, 2, 55, 46, 700122)),
        ),
    ]
