# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20170619_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='Goal_now1',
            field=models.TextField(default='goal3'),
        ),
        migrations.AddField(
            model_name='post1',
            name='Goal_now2',
            field=models.TextField(default='goal4'),
        ),
    ]
