# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20170626_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post1',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
