# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20170628_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='published_date',
        ),
    ]
