# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_remove_post1_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='Sanjeev')),
                ('Standard', models.TextField(default='Grade 7th')),
                ('How_do_I_feel_after_my_assignment', models.TextField()),
                ('What_I_will_do_different_next_week', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='update',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
