# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20170629_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='Sanjeev')),
                ('Standard', models.TextField(default='Grade 7th')),
                ('How_do_I_feel_after_my_assignment', models.TextField()),
                ('What_I_will_do_different_next_week', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
