# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20170629_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='How_do_I_feel_after_my_assignment',
            new_name='How_do_I_feel_after_my_assessment',
        ),
    ]
