# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20170630_0257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Week',
            new_name='Update1',
        ),
    ]
