# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_update1_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='update1',
            name='goalcompleted',
            field=models.TextField(default='1'),
        ),
    ]
