# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_update1_goalcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='Goal_now3',
            field=models.TextField(default='goal5'),
        ),
        migrations.AddField(
            model_name='post1',
            name='Goal_now4',
            field=models.TextField(default='goal6'),
        ),
    ]
