# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_auto_20170706_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='Goal_now1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal_now2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal_now3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal_now4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal_old1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post1',
            name='Goal_old2',
            field=models.TextField(default=''),
        ),
    ]
