# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_update_what_did_i_learn_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='allstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.TextField(default='7th')),
                ('Name', models.TextField(default='Sanjeev')),
            ],
        ),
        migrations.AlterField(
            model_name='post1',
            name='Standard',
            field=models.TextField(default='7th'),
        ),
        migrations.AlterField(
            model_name='update',
            name='Standard',
            field=models.TextField(default='7th'),
        ),
    ]
